services:
  jl-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
      - "9000:9000"
    volumes:
      - ..:/usr/src/app
    container_name: jl-dev
